name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Test Docs
      run: cargo doc
    - name: Commit Docs
      run: |
        rm -rf docs 
        cp -r target/doc docs 
        git config --local user.email "bot@goblinoid.co.uk"
        git config --local user.name "Github Actions Bot"
        git add .
        git commit -m"Commit doc updates" -a || echo "No changes to commit"
    - name: Push Docs
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
