name: Build and Test Rust

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Test Docs
      run: |
        export RUSTDOCFLAGS="-Dwarnings"
        cargo doc
    - name: Test Blog
      run: |
        cd pubs
        npm install
        npm run build
