name: Build and Push Rust Docs to GitHub Pages

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: ghpages
    - name: Merge main
      run: |
        git config --local user.email "bot@goblinoid.co.uk"
        git config --local user.name "Github Actions Bot"
        git merge origin/main
    - name: Build Docs
      run: cargo doc
    - name: Commit Docs
      run: |
        rm -rf docs 
        cp -r target/doc docs 
        git add .
        git commit -m"Commit doc updates" -a || echo "No changes to commit"
        git push
